### ISSUE TITLE
No reaction from E-Mail address provided in chrome web store

### ISSUE THREAD

**Issue by gregorwolf** [SAP/ui5-inspector#108]
Hello UI5 Inspector Team,

on 20th of August 2020 I've sent an E-Mail to sapmobileassembly@sap.com which is the one linked in the chrome web store

https://chrome.google.com/webstore/detail/ui5-inspector/bebecogbafbighhaildooiibipcnbngo

listing behind "Contact Developer". Unfortunately I haven't received any reply. Perhaps it would be better to link to the GitHub issues instead.

Best regards
Gregor

**Comment by jdichev** [comment]
Hello @gregorwolf,

The Google Chrome Webstore requires an email to create and account. This is also another organisation's email - the one that manages the SAP account in this respective store and colleagues are not specialised in UI5 Inspector.

For anything else, please contact us via the issues here and we will try our best to help.

Thanks and best regards,
Jordan
