### ISSUE TITLE
Inconsistent Version information shown in the UI5 Inspector

### ISSUE THREAD

**Issue by gregorwolf** [SAP/ui5-inspector#109]
Hello SAP UI5 Inspector Team,
 
For quite some time I‘m always annoyed that the SAPUI5 version shown when I click the UI5 Inspector icon is actually the OpenUI5 Version as you can see in the screenshot below where I compare it with the output of ctrl+shift+alt+s:
 
![image001](https://user-images.githubusercontent.com/2639535/92352404-4dfc2e80-f0de-11ea-853f-370f94521e0e.png)
 
The correct information is shown when you hover over the icon “This page is using SAPUI5 v1.80.2.
 
I would suggest that like in the SAPUI5 Diagnostics both versions should be shown in the pop-up.
 
Best regards
Gregor

**Comment by jdichev** [comment]
Hello @gregorwolf,

The fix of this issue will be included in the next release.

Thanks and best regards,
Jordan

**Comment by gregorwolf** [comment]
Hi @jdichev 

do you have information when the next released is planned?

Best regards
Gregor

**Comment by jdichev** [comment]
Hello @gregorwolf,

We don't have a fixed schedule yet, just waiting for a number of fixes and improvements to accumulate.

Rough estimate is new release should happen before end of year. I hope next year for a more frequent release schedule.

Best regards,
Jordan
