### ISSUE TITLE
UI5 Inspector outdated and removed from Google Webstore

### ISSUE THREAD

**Issue by sojimaxi** [SAP/ui5-inspector#128]
The UI5 Inspector available on the Google Chrome Webstore was version  0.9.6 and was published in 2015 but there seems to be updates on the master branch but no releases. 

It seems to have been removed from the Google Chrome Webstore. The link [https://chrome.google.com/webstore/detail/ui5-inspector/bebecogbafbighhaildooiibipcnbngo](https://chrome.google.com/webstore/detail/ui5-inspector/bebecogbafbighhaildooiibipcnbngo) returns a 404.

**Comment by jdichev** [comment]
Hello,

We are working on solving issues with the Google Chrome Webstore. It is not possible to forecast how long this will take. Meanwhile you can download the latest release from the releases section of this repository.

https://github.com/SAP/ui5-inspector/releases

Sorry for any inconvenience.

Thanks and best regards,
Jordan

**Comment by jdichev** [comment]
UI5 Inspector is back in Chrome Web Store.
