### ISSUE TITLE
Cannot inspect any element inside SAP Launchpad

### ISSUE THREAD

**Issue by MichaelFlucher** [SAP/ui5-inspector#133]
I have several Apps inside my SAP Launchpad I'd like to inspect. The Structure inside the UI5 tab only shows the whole App as one Element: `<sap.ushell.components.container.ApplicationContainer id="application-Item-List">`

I also can't use right click > Inspect UI5 control. Is this not supported yet?

**Comment by MichaelFlucher** [comment]
Hi @nnaydenow,
thanks for the hint. You are right, the SAP Launchpad Services embeds the HTML5 app using an iframe. 
Is there any possibility to debug it anyway?

**Comment by gregorwolf** [comment]
Hi @nnaydenow,

would it help to raise an incident via SAP Support in the Portal / Launchpad Service component to get this issue fixed?

**Comment by MichaelFlucher** [comment]
@gregorwolf as workaround for now I always search for `ui5appruntime.html` in the Networks tab and directly open the requested URL - quite ugly, but it works...

**Comment by jdichev** [comment]
Hello,
The possibility to use the UI5 Inspector across iframes on a specific page was added recently with https://github.com/SAP/ui5-inspector/commit/197dfd3bc6b7015249e4f4c3b99062fd7c56b3c2. It will be available after latest release becomes public.
Best regards,
Jordan

**Comment by jdichev** [comment]
Hello,

This feature result along with everything else that made it into the release is being evaluated as after the latest release is produced. After confirmation, we're going to publish the latest release via Chrome Web Store.

Best regards,
Jordan
