### ISSUE TITLE
Automatic release publishing to Chrome Web Store

### ISSUE THREAD

**Issue by gregorwolf** [SAP/ui5-inspector#141]
Today Version 0.9.11 was released. But it's not yet availalble in the Chrome Web Store. Seems that right now someone has to do the manual [Update your Chrome Web Store item](https://developer.chrome.com/docs/webstore/update/). But there is also [Chrome Web Store Publish API](https://developer.chrome.com/docs/webstore/using_webstore_api/). This API can be used either via this npm package: [chrome-webstore-upload](https://github.com/fregante/chrome-webstore-upload) or that GitHub Action [Chrome Extension upload & publish](https://github.com/marketplace/actions/chrome-extension-upload-publish).

**Comment by jdichev** [comment]
Hello Gregor,

It is on our internal roadmap to look into this topic. As mentioned on twitter, our bigger priority is to increase the frequency with which we push new releases.

Best regards,
Jordan

**Comment by gregorwolf** [comment]
Hi Jordan,

but doesn't the automation of the publishing process achieve exactly that?

CU
Gregor

**Comment by jdichev** [comment]
Hello Gregor,

Automating the upload of build zip will only partially help as we have other stages and issues with the release process.

This improvement is still on our roadmap and to date all other steps are automated as much as possible such as regularly building new versions and version management.

This issue will be updated when news happen in this direction.

Best regards,
Jordan

**Comment by gregorwolf** [comment]
Hi @jdichev,

any new regarding the automatic release?

**Comment by jdichev** [comment]
Hello @gregorwolf,

We'll consider that in the future. For now the creation of new versions of UI5 Inspector is scheduled to happen on a regular basis if there is enough increment and when it happens it is fully automated. After a new version is created a version is not automatically pushed to Chrome Web Store until it is validated by internal testing.

Therefore, everything that needs to be covered by an automated procedure is covered.

Best regards
