### ISSUE TITLE
In the release `0.9.11` the version number remains un-updated `0.9.10`

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-inspector#143]
In `manifest.json` version remained un-updated in the release `0.9.11`: `"version": "0.9.10"`.

**Comment by gregorwolf** [comment]
Have you seen #141 ?

**Comment by pubmikeb** [comment]
> Have you seen #141 ?

Yes, I've downloaded the `0.9.11` build from Github and there the version in manifest is `0.9.10`.

**Comment by MichaelFlucher** [comment]
Also the released `0.9.12` has in the `manifest.json` the version number `0.9.10`.

**Comment by jdichev** [comment]
This issue should have been resolved in latest version. Let us know if there is still inconsistency in versioning.
