### ISSUE TITLE
Support for OData V4 $batch requests in the OData Requests tab

### ISSUE THREAD

**Issue by gregorwolf** [SAP/ui5-inspector#144]
Hi @IlianaB,

do you have any plans to support also OData V4 $batch requests?

In the moment only the $batch request is shown as a folder but the details can't be opened:

![Screenshot 2021-12-09 at 14 47 33](https://user-images.githubusercontent.com/2639535/145408183-f8964ea3-0a8a-425a-bf03-f20ae7d4b94f.png)

With a OData V2 request this works just fine.

Best Regards
Gregor

**Comment by IlianaB** [comment]
Hello @gregorwolf ,

Recently we have merged https://github.com/SAP/ui5-inspector/pull/140 which should have fixed the problem. However, this fix is still not released. 
As a temporary solution, I can suggest you to use a downloaded version from the repository and work with it, until it's officially released.

Regards,
Iliana

**Comment by gregorwolf** [comment]
Woulf be better if #143 can be fixed to solve the version problem for everyone.

**Comment by jdichev** [comment]
Hello Gregor,
Sorry for delay. This issue should have been fixed with latest releases along with the referred version issue. Tested with internal test systems for Fiori Elements V4.
Best regards,
Jordan
