### ISSUE TITLE
Ui5 inspector is changing variable when debugging

### ISSUE THREAD

**Issue by sebbi08** [SAP/ui5-inspector#146]
Hi somehow the ui5 inspector is chanching local variables when debugging even non ui5 apps

![image](https://user-images.githubusercontent.com/9070136/148748546-e06a0a0e-4b7a-44bf-bee2-d7d4d167fd7b.png)

**Comment by dobrinyonkov** [comment]
Hi @sebbi08, 

sorry for the late reply. Could you provide more information about the use case you hit and how to reproduce the issue you're describing?

Thanks and Best Regards,
Dobrion
