### ISSUE TITLE
Model Information only shows [object Object] as data

### ISSUE THREAD

**Issue by MichaelFlucher** [SAP/ui5-inspector#161]
When I inspect an Element and navigate to Bindings the Model data is not shown anymore. Doesn't matter if it is an OData or JSON Binding. I only get something like this:

```
name: "modelName"
type: "sap.ui.model.json.JSONModel"
mode: "TwoWay"
data: [object Object]
```

UI5 Inspector Version is 0.9.13

**Comment by IlianaB** [comment]
Hello @MichaelFlucher ,

I have tried to reproduce the problem, but cannot see it. Can you provide public URL of the app, if possible?

Regards,
Iliana

**Comment by MichaelFlucher** [comment]
I found the issue coming from this change:
https://github.com/SAP/ui5-inspector/commit/457a5729fa12f6de7c53d11b887c99a9c7a53dba#diff-24bfd57139161e0e174e66df277fad5bc2d96905358fb7e00ccde42a8e35d0eeL184-R200
