### ISSUE TITLE
Your connection timed out. Please restart the dev tools panel and reload the page.

### ISSUE THREAD

**Issue by TelmoSoeiro** [SAP/ui5-inspector#168]
After update to 1.0.0, is constantly giving the message _"Your connection timed out. Please restart the dev tools panel and reload the page."_ after some time of usage on the UI5 tab.
To recovery "UI5 Inspector" I need to reload the page.

**Comment by skamok** [comment]
How I can install the previous version ?

**Comment by proehlen** [comment]
> How I can install the previous version ?

I just did it by:

1. Going to the releases page https://github.com/SAP/ui5-inspector/releases
2. Scroll down to version v0.9.13
3. Expand the Assets
4. Download the ui5inspector-v0.9.13.zip file
5. Unzip/extract the file contents
6. In chrome://extensions turn on "Developer mode"
7. Click the "Load unpacked" button
8. Select the folder that was created by extracting the earlier zip file
