### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by ClementRoyer** [SAP/ui5-inspector#169]
Hi everyone,

For the past week I have not been able to use the extension because it's not working anymore for me.
The extension show nothing when opened.

I have tried to :
- Clear cache
- Uninstall - clear cache - reinstall
- "Reload frame"
- Check the extension console

![image](https://user-images.githubusercontent.com/40796663/161937740-ef681db7-3edb-4921-ac48-ac01f07ca3fe.png)

![image](https://user-images.githubusercontent.com/40796663/161946737-213fed27-4285-4dbb-a945-17a189319762.png)

**Comment by ClementRoyer** [comment]
Hi, sorry for the late answer

I have the same Os and version:
Windows, Chrome Version 100.0.4896.75 (Build officiel) (64 bits)

**Comment by ClementRoyer** [comment]
Hi,

I also have the problem with an other computer, here is its info:
Windows, Chrome, Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by dobrinyonkov** [comment]
Hi everyone,

I was able to reproduce this issue to some level. For me, It only happens on the first install of the extension or if the port connection timeouts (#168) and then you try to use the inspector whitout refreshing the page:

For example: 
1. open a ui5 web page (ex. https://openui5nightly.hana.ondemand.com/)
2. install the extension 
3. open dev tools and UI5 panel without refreshing the web page

While we investigate this further and provide a stable solution, I was able to workaround this problem by refreshing the web page when the empty UI5 dev tools panel is shown. 
Please, try and confirm if that fixes the broken state of the inspector.

Thanks and Best Regards,
Dobrin

**Comment by ClementRoyer** [comment]
Hi,

First of all, big thanks for your help and your time.

For me it happens on every situation. I have the extension for at least a year, so this is not a fresh install and there is also no timeout. Just a blank screen. No matter what I do, clear cache, refresh page, private navigation, the ui5 inspector panel remain blank.
So I don't think you reproduced the same error, maybe the common point is that the ui5 inspector script can't be installed on page it navigates to, so it looks like your error, but you can fix it by refreshing the page which doesn't work for me.

Thank you for your help,
Clément

**Comment by ClementRoyer** [comment]
Also if I remember correctly when you are on a Fiori web page and click the extension you could see the version and other informations, here is what I have :
![image](https://user-images.githubusercontent.com/40796663/162888693-98071cd6-dbbd-48f0-a963-a0eba8b7cbff.png)

**Comment by sebastianomarchesini** [comment]
Hi guys, 
I have the same issue. For solve it, usually, meanwhile the control inspector is opened, try to touch some control (like open a select/combobox, change data, open a filter), make some event, and it's working. 

It's not a final solution, but it's a good workaround for now until is not solved.

**Comment by ChiaraDeDominicis-Reg** [comment]
@strawherotk solution worked form me: after turning off and on again "Developer mode" in Chrome's Extension Manager tab and refreshing the application page everything seems fine.
I'm happily using ui5-inspector since 2018 <3! Thanks for all your efforts

**Comment by ClementRoyer** [comment]
Hey everyone,

Sadly, none of the above solution worked for me 😢 
I don't have developer mode enable for extension (even with it doesn't work), and triggering an event don't change anything on my ui5 inspector panel.

This extension is so helpful, it's very sad to not being able to use it.
Hope a fix come very soon !

**Comment by dobrinyonkov** [comment]
Hi everyone! 

Still, I'm not able to identify the root cause of this issue. I was able to reproduce it on some of my colleagues Windows machines and we managed to fix the problem by re-installing Google Chrome.

You can try and delete the extension cache and if that doesn't works, try to reinstall Google Chrome. Make sure you keep your profile data and any backups up to date.

NOTE: Also, for the latest ui5-inspector to work Google Chrome needs to be updated to atleast 93 version, as version 92 and below, required the service worker to be on root level.

Thanks and Best Regards,
Dobrin

**Comment by ClementRoyer** [comment]
Hello,

My company updated Chrome to the latest vestion and reinstalled it on my computer, it fixed the issue.
Thank's a lot for your time and your quick answers.

Have a good day !!
