### ISSUE TITLE
firefox support

### ISSUE THREAD

**Issue by DetachHead** [SAP/ui5-inspector#182]

**Comment by jdichev** [comment]
Hello,
We have been considering this for a long time now and it is good that you have raised it. I can share that we plan to work this in the future but cannot commit to a specific time line at the moment. Stay tuned as this issue should be updated in case of news.
Best regards,
Jordan

**Comment by DetachHead** [comment]
@jdichev is this it? https://addons.mozilla.org/en-US/firefox/addon/ui5-inspector/

there doesn't seem to be any mention of the firefox version anywhere, perhaps https://sap.github.io/ui5-inspector/ should be updated to link to it if the user is on firefox?
