### ISSUE TITLE
Support for Focus Mode in Microsoft Edge

### ISSUE THREAD

**Issue by benutzer193** [SAP/ui5-inspector#185]
## Description

In newer releases, Microsoft introduced the [Focus Mode](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/experimental-features/focus-mode) in Edge.
When this Mode is enabled, it is impossible to enable and access the UI5 tab used by the UI5 inspector extension.

### OpenUI5/SAPUI5 version:
any

### Browser/version:
Microsoft Edge Version 103.0.1264.49 (Official build) (64-bit)

### URL (minimal example if possible):
App independent

### User/password (if required and possible - do not post any confidential information here):
N/A

### Steps to reproduce the problem:
1. enable Focus Mode, as detailed [here](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/experimental-features/focus-mode#enable-focus-mode)
2. try to access the UI5 tab

### What is the expected result?
UI5 Tab is available automatically or can be added via the `+` Button to the Edge DevTools, if the Focus Mode is active

### What happens instead?
UI5 Tab is not available and can't be added to the Edge DevTools, if the Focus Mode is active

### Any other information? (attach screenshots if possible)

Without Focus Mode:
![image](https://user-images.githubusercontent.com/9975220/178235324-3f6066c6-a1a4-4ac5-853b-cca53ab6cad4.png)

With Focus Mode:
![image](https://user-images.githubusercontent.com/9975220/178235545-e07e852a-e8ca-44ae-a7e6-52d66de67a28.png)

**Comment by proehlen** [comment]
@benutzer193 This started working for me in the last few days I think.  Might have been an Edge update or maybe the extension got updated:

![image](https://user-images.githubusercontent.com/8384068/206359663-169d0ea2-dbf5-49a8-9749-cd24534eded5.png)

**Comment by benutzer193** [comment]
Thanks for the notification, it is working for me now as well.
I assume it is related to https://github.com/MicrosoftEdge/DevTools/issues/31.
