### ISSUE TITLE
Publishing UI5 inspector to Microsoft Extension Store?

### ISSUE THREAD

**Issue by the-docta** [SAP/ui5-inspector#228]
Would it be possible to publish UI5 Inspector to Micrisoft Extensions Store?

would be extremely handy if the corporate forbids installing Chrome, and also blocks Chrome Extensions in Edge, and also blocks "Load unpacked" using policies.

The only allowed source for extensions is the MS Webstore for extensions

Thanks!

**Comment by jdichev** [comment]
Hello @the-docta,

I cannot reveal internal details. Approval of a store and publishing in it is not done directly by the UI5 Inspector team. What I can do is to pass your feedback to the responsible colleagues and I hope action is taken as we've got similar feedback in the past and this would be really beneficial.

Thanks and regards,
Jordan
