### ISSUE TITLE
firefox support

### ISSUE THREAD

**Issue by DetachHead** [SAP/ui5-inspector#237]
#182 was closed as completed with no comment, but there does not seem to be a firefox version available. there's [this](https://addons.mozilla.org/en-US/firefox/addon/ui5-inspector/) but it was last updated in 2018.

**Comment by jdichev** [comment]
Hello, @DetachHead this is not an official version of UI5 Inspector and is not published by SAP. UI5 Inspector is only published on the Chrome Web Store.

**Comment by KotlinIsland** [comment]
@jdichev Can we see an official version published on the Firefox Web Store?
