### ISSUE TITLE
After opening the ui5 inspector whole page is frozen.

### ISSUE THREAD

**Issue by maplestoria** [SAP/ui5-inspector#245]
many errors occurred, see the below screenshots

<img width="677" alt="Screenshot 2023-07-11 at 16 46 37" src="https://github.com/SAP/ui5-inspector/assets/25701092/23670574-018a-494a-96ac-3ab712077cc3">
<img width="660" alt="Screenshot 2023-07-11 at 16 53 34" src="https://github.com/SAP/ui5-inspector/assets/25701092/46b2b432-e634-436f-a254-0c1b15a0b6f2">
<img width="653" alt="Screenshot 2023-07-11 at 16 53 47" src="https://github.com/SAP/ui5-inspector/assets/25701092/b5046955-bc12-4ad5-a81c-3a51f292225a">

**Comment by dobrinyonkov** [comment]
Hi @maplestoria, 

It seems that we are unable to reproduce this issue. 
Could you provide a "Step-by-step" guide on when you face those errors? If possible, include the page you're inspecting and some device information (Windows, MacOS, Chrome version, etc).

Thanks and Best Regards,
Dobrin

**Comment by maplestoria** [comment]
Hi,
I found it may caused by a large JSONModel with circular references, therefore I am closing this issue.
