### ISSUE TITLE
Inspector doesn't work at new version 1.6.2

### ISSUE THREAD

**Issue by Ilichev-vlad** [SAP/ui5-inspector#250]
![123](https://github.com/SAP/ui5-inspector/assets/60879718/6b6fc5bf-a3fb-479c-8086-606a9037be01)

**Comment by TelmoSoeiro** [comment]
> ![123](https://user-images.githubusercontent.com/60879718/262977479-6b6fc5bf-a3fb-479c-8086-606a9037be01.png)


`Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at _getDebugModeInfo (ToolsAPI.js:66:41)
    at Object._getFrameworkInformation [as getFrameworkInformation] (ToolsAPI.js:111:32)
    at get-initial-information (main.js:82:49)
    at HTMLDocument.communicationWithContentScript (main.js:300:35)`

Same problem here.

**Comment by jdichev** [comment]
Hello,

Working on a solution in the team. Expect updates soon.
Meanwhile, if necessary there is still the option to use an older version as an unpacked extension.

Best regards,
Jordan

**Comment by albrecmi** [comment]
> Hello,
> 
> Working on a solution in the team. Expect updates soon. Meanwhile, if necessary there is still the option to use an older version as an unpacked extension.
> 
> Best regards, Jordan

Hi Jordan, where to get the older version an how to add it to chrome?

**Comment by skamok** [comment]
> > Hello,
> > Working on a solution in the team. Expect updates soon. Meanwhile, if necessary there is still the option to use an older version as an unpacked extension.
> > Best regards, Jordan
> 
> Hi @jdichev, where to get the older version an how to add it to chrome?

1. Download previous release https://github.com/SAP/ui5-inspector/releases
2. Unpack
3. In Chrome open as url: chrome://extensions/
4. Check “Developer mode” and then click "Load unpacked extension..."
5. From the newly opened window select the unpacked release
6. Restart Chrome

**Comment by TelmoSoeiro** [comment]
> > > Hello,
> > > Working on a solution in the team. Expect updates soon. Meanwhile, if necessary there is still the option to use an older version as an unpacked extension.
> > > Best regards, Jordan
> > 
> > 
> > Hi @jdichev, where to get the older version an how to add it to chrome?
> 
>     1. Download previous release https://github.com/SAP/ui5-inspector/releases
> 
>     2. Unpack
> 
>     3. In Chrome open as url: chrome://extensions/
> 
>     4. Check “Developer mode” and then click "Load unpacked extension..."
> 
>     5. From the newly opened window select the unpacked release
> 
>     6. Restart Chrome

Thank you. Tried and it works with version 1.6.1.
Don't forget to remove the latest version "UI5 Inspector 1.6.2" on the extension management.

Best Regards,
Telmo.

**Comment by LudkaMotylikova** [comment]
1.6.1. works
