### ISSUE TITLE
Empty console for inspector

### ISSUE THREAD

**Issue by vishnucta** [SAP/ui5-inspector#252]
![image](https://github.com/SAP/ui5-inspector/assets/3929099/b30983c2-c105-4869-8ff6-4c02d1d13921)

**Comment by vishnucta** [comment]
![image](https://github.com/SAP/ui5-inspector/assets/3929099/96242e49-73ae-499e-928d-763fb11349a0)


I am not sure whether this screen is relevant but i found this issue in console.

**Comment by skamok** [comment]
https://github.com/SAP/ui5-inspector/issues/250

**Comment by yanaminkova** [comment]
Hello @vishnucta,

This issue is duplicate to https://github.com/SAP/ui5-inspector/issues/250, which was fixed with https://github.com/SAP/ui5-inspector/pull/251 and will be part of the new relеase.

Thanks and Best regards,
Yana
