### ISSUE TITLE
UI5 Inspector doesnt work on Chrome

### ISSUE THREAD

**Issue by LudkaMotylikova** [SAP/ui5-inspector#253]
Hi,
I use UI5 Inspector but last 2 weeks it doesnt work on Chrome. I see blank page. Is UI5 Inspector down or should I do something to fix it on my side? I will be happy you answer me because I use on daily basis and my job is much faster and easier with it.

**Comment by skamok** [comment]
> Hi, I use UI5 Inspector but last 2 weeks it doesnt work on Chrome. I see blank page. Is UI5 Inspector down or should I do something to fix it on my side? I will be happy you answer me because I use on daily basis and my job is much faster and easier with it.

https://github.com/SAP/ui5-inspector/issues/250

**Comment by yanaminkova** [comment]
Hello @LudkaMotylikova,

This issue is duplicate to #250, which was fixed with https://github.com/SAP/ui5-inspector/pull/251 and will be part of the new relase.

Thanks and Best regards,
Yana
