### ISSUE TITLE
Inspector doesn't work at new version 1.6.3

### ISSUE THREAD

**Issue by Ilichev-vlad** [SAP/ui5-inspector#256]
![ui5 inspector doesn't work](https://github.com/SAP/ui5-inspector/assets/60879718/11998bd4-b604-4c1c-9ad0-b05d708b2e61)

**Comment by dobrinyonkov** [comment]
Hi @Ilichev-vlad , 

Could you provide more information about the use case you hit and how to reproduce the issue you're describing?

Browser, application, OS, etc.

Kind Regards,
Dobrin

**Comment by CLVNSwan** [comment]
Hello, 

same here. Inspector wont add UI5-TAB in Chrome debugger
![grafik](https://github.com/SAP/ui5-inspector/assets/33055891/4ad38cfb-b0a4-4532-95d4-8185fc24ad58)

Chrome Version: 
Version 117.0.5938.63

UI5 Inspector Version: 
1.6.3

SAPUI5 Version: 
1.108.5
(but also on current version on ui5.sap.com)

**Comment by PetyaMarkovaBogdanova** [comment]
Hello @CLVNSwan , @Ilichev-vlad ,
can I, please, ask you to update your browser to the latest version and try again?
Please, let me know if the issue still persists.
Thank you!

Best regards,
Petya Markova.
(UI5 Inspector Developer)

**Comment by MedusaLuchs85** [comment]
Same to me. Chrome was updated to the latest version (Version 119.0.6045.105 (Offizieller Build) (arm64)). UI5 Inspector (1.6.3) is not working. Content menu to inspect UI5 Controls doesn't show the control inspection view ...

![image](https://github.com/SAP/ui5-inspector/assets/67327280/72eb5b9d-99eb-40e9-b93c-9f3b0649de33)

**Comment by CLVNSwan** [comment]
@PetyaMarkovaBogdanova 
The problem still exists in 

Chrome Version: 119.0.6045.106
UI5 Inspector Version: 1.6.3
Windows 11

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @CLVNSwan ,
we just released a new version 1.6.4.
Can you, please, retest and give your feedback again?
Thank you!

**Comment by CLVNSwan** [comment]
@PetyaMarkovaBogdanova the AddOn is working fine again 🥳
Thank you too!

**Comment by PetyaMarkovaBogdanova** [comment]
We are very glad to hear!
Apologies for our delay.
Have a happy debugging :)
Kind regards,
Petya Markova.
