### ISSUE TITLE
Inspector tooltip is blank

### ISSUE THREAD

**Issue by dimovpetar** [SAP/ui5-inspector#265]
![image](https://github.com/SAP/ui5-inspector/assets/32839090/ca223a67-9607-475c-a576-1d4bbecb6920)
In the past I used this tooltip to see the loaded UI5 version on the page, however, from some time it appears blank.

Steps to reproduce the issue:

1. Open https://ui5.sap.com/
2. Click on the inspector icon

OS: Windows 11
Browser: Version 125.0.6422.113 (Official Build) (64-bit)
UI5 Inspector: 1.6.3

![image](https://github.com/SAP/ui5-inspector/assets/32839090/c097d0d8-ea87-4c83-83b2-4c6b2581b7ec)

**Comment by PetyaMarkovaBogdanova** [comment]
Hi Petar,
the issue has been fixed in version 1.6.4
Please, update your extension and retest.
Thank you!
Best regards,
Petya Markova.
(UI5 Inspector Developer)

**Comment by dimovpetar** [comment]
@PetyaMarkovaBogdanova thanks :)
Tested and it works in 1.6.4.
