### ISSUE TITLE
Preview of the batch for OData Request is empty now

### ISSUE THREAD

**Issue by gyq180** [SAP/ui5-inspector#272]
Today, chrome update to Version 130.0.6723.59 (Official Build) (64-bit), then the ui5 has this issue.
![image](https://github.com/user-attachments/assets/091c44a3-8f7f-474f-8ad1-eb07c369a25e)
![image](https://github.com/user-attachments/assets/10421a0d-eae3-40b1-acd6-158ecb3b3632)

**Comment by gyq180** [comment]
Hello all, do you has a plan to publish a new version for this issue?

**Comment by MDagni** [comment]
Hi @gyq180 . I want this fix to be released as well. For the time being, I cloned the latest code from github and built on my PC. It works well.

The instructions are here: https://github.com/SAP/ui5-inspector?tab=readme-ov-file#local-development-and-use
I used "git clone https://github.com/SAP/ui5-inspector.git" for the first step.

@kineticjs It would be really nice if this was published as a new release.

**Comment by gyq180** [comment]
> Hi @gyq180 . I want this fix to be released as well. For the time being, I cloned the latest code from github and built on my PC. It works well.
> 
> The instructions are here: https://github.com/SAP/ui5-inspector?tab=readme-ov-file#local-development-and-use I used "git clone https://github.com/SAP/ui5-inspector.git" for the first step.
> 
> @kineticjs It would be really nice if this was published as a new release.

I forked this project and publish the lastest version in my repository, it works well too. [https://github.com/gyq180/ui5-inspector](https://github.com/gyq180/ui5-inspector )
