### ISSUE TITLE
[BUG] OData tab broken

### ISSUE THREAD

**Issue by jvanattedev** [SAP/ui5-inspector#275]
Since Chrome 1.130, the OData request view is broken and shows no data. The panel on the right is empty and the folders with the batch requests cannot be opened.
![image](https://github.com/user-attachments/assets/509c3b2e-eeae-4c3f-b84e-64fc4f6a2a89)

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @jvanattedev,
thank you for reporting this issue!
It has been fixed in the new released version 1.6.6.
You can update to it.
Best regards,
Petya Markova.
(UI5 Developer)
