### ISSUE TITLE
More details and overview in the Bindings tab

### ISSUE THREAD

**Issue by SeeSharpSoft** [SAP/ui5-inspector#30]
This is a proposal for enhancing the Bindings tab.
## Motivation

What I would like to see as a developer when investigating into the binding of a property:
- the model => name, type and content
- the context => content
- the path
- the value from the model
- the formatted value
- the formatter function
- the value type
- the binding mode

Due the support of multi-binding, showing the model/path/value gets more complex. However, I would like to see all parts of the binding including the individual models, paths and values.

Furthermore I would like to change a bound value in the model and see its change reflected in the property. This would especially be useful for UI related bindings, e.g. visible, expanded, listMode, etc.
## How it might look like

My proposal for the bindings tab is shown in the following picture:

![image](https://cloud.githubusercontent.com/assets/3205800/10269761/01a6bed0-6ae0-11e5-9d66-8793f8a6d9b7.png)

Editing the values is enabled for all models with TwoWay bindingmode.

![image](https://cloud.githubusercontent.com/assets/3205800/10269763/0908db22-6ae0-11e5-9716-84f557aa4305.png)

Changing the bound model value is not only reflected in the model information but also in the property and in the UI itself.
## Implementation

A running version is available here: https://github.com/SeeSharpSoft/ui5-inspector/commits/BINDINGS_FEATURE_MODEL_DETAILS

**Please note:** This is not a final commit. Besides certain TODOs it also needs some conceptual rework.

I am looking forward getting feedback on this.

**Comment by Chariyski** [comment]
Hi Martin,

We will have a meeting with our PO for your proposition  and I will inform you about the decision. Unfortunately this will happen next week :)

Best regards,
Krasimir

**Comment by Chariyski** [comment]
Hello @SeeSharpSoft,

We will provide similar functionality in a future version of the extension. Once the version is decided I will add the request to the proper milestone.

Best regards,
Krasimir

**Comment by limpbizkit107** [comment]
Hi @SeeSharpSoft ,

We have merged your implementation of the feature with some small modifications for the cases where we found bugs. For the moment we just displaying the information in the binding tab a further implementation of editing the bindings will be planned soon. Big Thank you for your contribution it was very helpful !

Regards,
Stefan
