### ISSUE TITLE
Make configuration editable

### ISSUE THREAD

**Issue by Hirse** [SAP/ui5-inspector#35]
Thanks for this great extension.

I have one enhancement / feature request:
It would be good if the configuration could be edited in the same way as the properties of a control.
So for example, change theme, rtl or debug mode.

**Comment by Chariyski** [comment]
Hello @Hirse,

Thank you for the feature request.
We have also thought about it and I will inform you, when we clarify the subject.

Best regards,
Chariyski

**Comment by Chariyski** [comment]
Hello @Hirse,

We will provide similar functionality in the future versions of the extension. Once the version is decided I will add the request to the proper milestone.

Best regards,
Krasimir

**Comment by Hirse** [comment]
Sounds good, thanks.

**Comment by SvetoslavSpasov** [comment]
Hi @Hirse,

We are currently having ongoing discussions about the support tools alignment. So far it is decided to make editable configuration in another tool (could be diagnostics window or something else).

Thanks & Best Regards,
Svetoslav
