### ISSUE TITLE
detectUI5 throws an error

### ISSUE THREAD

**Issue by ShtiliyanUzunov** [SAP/ui5-inspector#41]
On row 33 in detectUI5.js 
if (sap.ui.require) {
.....

I get an error
Uncaught TypeError: Cannot read property 'require' of undefined.
Add a check if sap.ui exists

I have the window.sap variable defined, but no ui is defined

**Comment by Chariyski** [comment]
Hi @ShtiliyanUzunov,

The issue is fixed and the code will be available with the next version.

Best regards,
Krasi
