### ISSUE TITLE
UI5 Inspector not detecting UI5

### ISSUE THREAD

**Issue by kevindeuel** [SAP/ui5-inspector#48]
Hi, I have added the UI5 Inspector to Chrome and when I run on browser from SAP Cloud Web IDE it is returning:

There is no OpenUI5/SAPUI5 found on this page

My friend sitting next to me with the same setup is able to use the add-on without issue. 

Any ideas?

**Comment by Chariyski** [comment]
Hi @kevindeuel,

Can you provide more information about the issue?
Please use https://github.com/SAP/ui5-inspector/blob/master/docs/bugreport_template.txt

**Comment by Chariyski** [comment]
Hi @kevindeuel,

this ticket is on 'author action' for more than 2 weeks without reaction.
Therefore this ticket is closed. If the ticket is still relevant please provide
 the requested information.

Best regards,
Chariyski
