### ISSUE TITLE
jQuery.sap.assert fires when inspecting controls with composite bindings

### ISSUE THREAD

**Issue by Frank683** [SAP/ui5-inspector#54]
Whenever I inspect a control which has a composite binding jQuery.sap.assert fires n times. One time for every part of the composite binding.

This is extremely annoying and I would appreciate if this could be suppressed.

![20160128_094820](https://cloud.githubusercontent.com/assets/14088575/12639423/92e407bc-c5a4-11e5-8b1d-f3159fd487a3.png)

**Comment by Frank683** [comment]
Huh, nothing?!?
Anyone here??

**Comment by NStoichkov** [comment]
Hi Frank,
Thanks for reporting, we are currently checking this issue.
Best Regards,
Nikolay

**Comment by limpbizkit107** [comment]
Hi the following issue is fixed with c81cffe3611d640923b99d4115ea77e8a5548b5d commit and it will be available in version 0.9.5.
