### ISSUE TITLE
Error "There is no OpenUI5/SAPUI5 found on this page'

### ISSUE THREAD

**Issue by chongchin** [SAP/ui5-inspector#57]
I open an SAP Sample Frori Application, "Approve Purchase Order'. When I select a UI5 control (button or Text control, right click, an select "Inspect UI5 Control", the UI5 tab  displays "There is no OpenUI5/SAPUI5 found on this page"

**Comment by Chariyski** [comment]
Hi @chongchin,

Can you check if that app is not in <iframe>. If this is the case, currently the extension is not working with iframes.

Best regards.

**Comment by chongchin** [comment]
Hi Chariyski,  
     I am not sure what is meant by "iframe". The application is SAP sample "Approve Purchase Order" application that comes as a sample in SAP Web IDE installation. Please help as I need to see the data binding of the UI5 controls to understand the app. Thank you. 
Best Regards
Chong Chin

**Comment by Chariyski** [comment]
@chongchin 

iframe is an HTML tag.

SAP Web IDE is using iframes for displaying the sample. Try opening the sample in new tab without Web IDE preview.

**Comment by chongchin** [comment]
Hi Chariyski,
       
    My company is a SAPB1 partner, and we new to Friori app. How do I open the sample without Web IDE preview. I tried to open the testFLPService.html file in Google Chrome. But nothing happens. To run this app in Web IDE, I would right click this file, then  "Run" > "Run with Mock Data". Thanks.

**Comment by chongchin** [comment]
Hi Chariyski,
OK. I manage to do so. Right click the html file, then choose "Run as Web Application". 
Thank you very much for your prompt reply. You have been a great help to us.
