### ISSUE TITLE
Silent Failure when data model contains methods

### ISSUE THREAD

**Issue by jdesjean** [SAP/ui5-inspector#58]
Hi,

I tried the extension on an UI5 app we have and noticed that some of the nodes in our tree couldn't be inspected. After some debugging, I noticed in /scripts/content/main.js@L91 detectEvent.detail is null if any of the property in detectEvent.detail is a function. For a better understanding of the problem, please read: http://stackoverflow.com/questions/28699159/customevent-detail-tainted.
My suggestion to fix this problem would be to add a function at /scripts/modules/injected/message.js@L13 that does a copy of the detail without the functions.

Cheers,
Jean-Francois

**Comment by limpbizkit107** [comment]
H iJean-Francois,

The issue is fixed. Thank you for your findings.

Regards,
Stefan Minchev
