### ISSUE TITLE
UI5 Inspector failed  No file

### ISSUE THREAD

**Issue by mary2003** [SAP/ui5-inspector#59]
Download error when Im trying to get the UI5 Inspector extension for  Chrome.

What can I do ??

Best regards
María Elena

**Comment by matz3** [comment]
I guess you tried to add the extension via the Chrome Web Store, right?
https://chrome.google.com/webstore/detail/ui5-inspector/bebecogbafbighhaildooiibipcnbngo

Is there a specific error which pops up? Without more information I am not sure if we can help you.

**Comment by mary2003** [comment]
Helo,

When I try to download UI5 Inspector it happenned:

View the images.......

Best regards
Maria Elena

**Comment by matz3** [comment]
@mary2003 sorry, I can not see any image. Could you please try to upload them on GitHub rather than attaching to your email reply?

**Comment by mary2003** [comment]
Hi,

The image is: 

![ui5 inspector error](https://cloud.githubusercontent.com/assets/17704093/15539432/64a87ec4-2250-11e6-946b-7748c85f3ab7.png)

**Comment by matz3** [comment]
Are you able to install other Chrome Extensions from the store?
This looks like an issue with the store or your local installation, not with the extension itself.
