### ISSUE TITLE
Unable to read in dark DevTools.

### ISSUE THREAD

**Issue by gluons** [SAP/ui5-inspector#60]
It's really hard to read in Chrome DevTools with dark theme.

<img width="947" alt="default" src="https://cloud.githubusercontent.com/assets/4688092/23641204/b8ee2fdc-0324-11e7-80cd-aeb4e2bdb54a.PNG">

<img width="956" alt="default" src="https://cloud.githubusercontent.com/assets/4688092/23641162/803d693c-0324-11e7-97bd-a8f032357582.PNG">

**Comment by aleksandrenko** [comment]
The theme was created without the dark theme in mind. Sorry :)
Feel free to make a pull request with a new/dark theme styles.

**Comment by SvetoslavSpasov** [comment]
Hi @gluons I've added a new dark theme.
Best Regards,
Svetoslav

**Comment by gluons** [comment]
Thank you. 😄
