### ISSUE TITLE
Does not work with SAP Web IDE

### ISSUE THREAD

**Issue by krisho007** [SAP/ui5-inspector#78]
When I run the application from SAP Web IDE, and try to use the UI5 Inspector to troubleshoot the app, it says "There is no OpenUI5/SAPUI5 found on this page" (in UI5 tab of the DevTools).

**Comment by limpbizkit107** [comment]
Hi @krisho007 ,

Thank you for reporting this issue!
We will investigate the problem. 
Maybe if you can give us some link to the application or the place where you find it not working so we can test it? It would be very helpful.

Regards,
Stefan

**Comment by krisho007** [comment]
I see that it is working after the latest update.
