### ISSUE TITLE
UI5-inspector extension is not working with Chrome

### ISSUE THREAD

**Issue by Sagartheocean** [SAP/ui5-inspector#79]
Hi,

I am newbie here in UI5. We want to automate the UI5 application and hence we have installed the extension.

I have installed the extension but it is showing disabled.

Chrome Version 70.0.3538.77 (Official Build) (64-bit)

Can you please help me to resolve the issue?

Thanks & Regards,
Sagar

**Comment by limpbizkit107** [comment]
Hi,
The UI5 Inspector is used for inspecting applications that are using OpenUI5/SAPUI5 framework.
I don't think that automating any UI5 application with UI5-Inspector is a good idea at all. 
The main porpoise of the extension is to help developers see and change the structure of the application that they are building, just like "Inspect" tab in Google Chrome for example.

The extension is become active only when the content of the page that you are viewing contain OpenUI5 or SapUI5 elements or applications. This is the reason why you may see the extension as disabled in your case.

Regards,
Stefan
