### ISSUE TITLE
Firefox addon

### ISSUE THREAD

**Issue by dakra** [SAP/ui5-inspector#82]
I see there is https://addons.mozilla.org/en-US/firefox/addon/ui5-inspector/ but it's not from an SAP account. Is the above addon official or are there plans to officially support Firefox?

**Comment by limpbizkit107** [comment]
Hi @dakra,

Yes the Firefox add-on that you mention is not by SAP and we can not support it.

Further more there are plans to introduce the UI5 Inspector to Firefox, but still there are internal discussions and planning that needs to be done, so we can released it officially.

At the moment i can't give you exact date or deadline.

I hope that answer your question.

Regards,
Stefan

**Comment by gluons** [comment]
Will this extension support Firefox in the future? I don't use Chrome browser.

**Comment by thunermay** [comment]
How is the state? It shouldn't be so big of a problem, should it? That would be awesome if this works because I'm using Firefox as my main Browser and it should be supported as well... 
Thanks!
