### ISSUE TITLE
Missing explicit Privacy Statement 

### ISSUE THREAD

**Issue by c50319** [SAP/ui5-inspector#84]
Ladies and Gentlemen, 
 
I would like to use this Extension.
 
My Company, however, has restrictions that only internally released extensions can be installed. For each extension to be included in the Company-owned Chrome Extension catalog we need a privacy statement confirming which data the application stores in the cloud and when it will be deleted. 
This can be a privacy statement on the website of the extension, or a corresponding statement by email from the manufacturer or similar. 
The statement must explicitly refer to the extension. Can you please provide this for your extension?
 
Thank you for your support.
 
Mit freundlichen Grüßen /Kind regards

**Comment by jdichev** [comment]
Hello, 

We will add such notice.

To be clear the UI5 Inspector does not in any way collect or process data but we will make this clear in the repository.

Thanks

**Comment by jdichev** [comment]
Hello,

Privacy statement added to extension's page: https://chrome.google.com/webstore/detail/ui5-inspector/bebecogbafbighhaildooiibipcnbngo

Best regards,
Jordan
