### ISSUE TITLE
Does not scroll to nearest UI5 control

### ISSUE THREAD

**Issue by ashwinmenkudle** [SAP/ui5-inspector#86]
Does not scroll to nearest UI5 control when switched from Elements tab to UI5 tab

Geeting error on devtools
Blocked autofocusing on a form control in a cross-origin subframe.
main.js:699
code line 
```js
var desiredViewBottomPosition = this._treeContainer.offsetHeight - this._treeContainer.offsetTop + this._treeContainer.scrollTop;
```

**Comment by jdichev** [comment]
Hello @ashwinmenkudle,

Could you please provide an isolated sample where we can reproduce the issue or send a link to a publicly available page?

Thanks and regards,
Jordan

**Comment by ashwinmenkudle** [comment]
The issue can be closed. This is no longer reproducible.
